spec-version: 0.37.0

name: waspc
version: 0.16.3
description: |
  Please see the README on GitHub at <https://github.com/wasp-lang/wasp/waspc#readme>
github: wasp-lang/wasp
author: Wasp Team
# TODO: update the email once we setup @wasp.sh email.
maintainer: team@wasp-lang.dev
copyright: Wasp, Inc.
license: MIT

tested-with:
  - GHC == 8.10.7

extra-source-files:
  - README.md
  - ChangeLog.md

data-dir: data/
data-files:
  - "Cli/**/*"
  - "Cli/templates/skeleton/.*" # We make sure to include the dot files in the skeleton template.
  - "Generator/**/*"
  - "Lsp/**/*"
  # For each package, we declare its root directory plus its dist directory, so that the
  # `node_modules` is not included in the data files.
  - "packages/*/*"
  - "packages/*/dist/**/*"

_common:
  - &common_all
    language: Haskell2010
    ghc-options:
      - -j
      - -Wall
      # -optP-Wno-nonportable-include-path avoids warning caused by .../- autogen/cabal_macros.h. on OSX.
      - -optP-Wno-nonportable-include-path
      # -fwrite-ide-info and -hiedir=.hie tell GHC to write compile-time - information about the code
      # to .hie directory. This information can then be used by other - tools, e.g. stan (static analyzer).
      - -fwrite-ide-info
      - -hiedir=.hie
    default-extensions:
      - OverloadedStrings
      - TemplateHaskell
      - QuasiQuotes
      - ScopedTypeVariables
      - LambdaCase
      - FlexibleContexts
      - MultiParamTypeClasses
      - DisambiguateRecordFields
  - &common_exe
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

# Top-level options are inherited by all components.
<<: *common_all

library:
  source-dirs: src
  build-tools:
    - alex
  generated-other-modules:
    - Paths_waspc
  dependencies:
    aeson-pretty: "^>= 0.8"
    aeson: "^>= 1.5.6"
    # 'array' is used by code generated by Alex for src/Analyzer/Parser/Lexer.x
    array: "^>= 0.5.4"
    async: "^>= 2.2.4"
    base: ">= 4.7 && < 5"
    bytestring: "^>= 0.10.12"
    conduit-extra: "^>= 1.3.5"
    conduit: "^>= 1.3.4"
    containers: "^>= 0.6.5"
    cryptohash-sha256: "^>= 0.11.102"
    cryptonite: "^>= 0.29"
    deepseq: "^>= 1.4.4"
    dir-traverse: "^>= 0.2.3"
    directory: "^>= 1.3.6 && < 1.4"
    dotenv: "^>= 0.10.0"
    exceptions: "^>= 0.10.4"
    extra: "^>= 1.7.10"
    filepath: "^>= 1.4.2"
    fsnotify: "^>= 0.3.0"
    Glob: "^>= 0.10.2"
    http-conduit: "^>= 2.3.8"
    mtl: "^>= 2.2.2"
    mustache: "^>= 2.3.2"
    neat-interpolation: "^>=0.5.1.3"
    network: "^>= 3.1.2"
    parsec: "^>= 3.1.14"
    path-io: "^>= 1.6.3"
    path: "^>= 0.9.2"
    pretty-simple: "^>= 4.1.2"
    process: "^>= 1.6.17"
    regex-tdfa: "^>= 1.3.1"
    split: "^>= 0.2.3"
    strong-path: "^>= 1.1.4"
    template-haskell: "^>= 2.16.0"
    text: "^>= 1.2.4"
    time: "^>= 1.9.3"
    unliftio: "^>= 0.2.20"
    unordered-containers: "^>= 0.2.16"
    utf8-string: "^>= 1.0.2"
    uuid: "^>= 1.3.15"

internal-libraries:
  waspls:
    source-dirs: waspls/src
    dependencies:
      aeson-pretty:
      aeson:
      async: "^>=2.2.4"
      base:
      data-default: "^>=0.7.1.1"
      deepseq:
      directory: "^>= 1.3.6.0"
      filepath:
      hashable: "^>=1.3.5.0"
      hslogger: "^>=1.3.1.0"
      lens: "^>=5.1"
      lsp: "^>=1.4.0.0"
      lsp-types: "^>=1.4.0.1"
      mtl:
      mustache: "^>=2.3.2"
      path:
      stm: "^>=2.5.1.0"
      stm-containers: "^>=1.2"
      strong-path:
      text:
      transformers: "^>=0.5.6.2"
      unliftio-core:
      unordered-containers:
      utf8-string:
      waspc:

  cli-lib:
    source-dirs: cli/src
    generated-other-modules:
      - Paths_waspc
    dependencies:
      aeson-pretty:
      aeson:
      async:
      base:
      bytestring: "^>= 0.10.12"
      cryptonite:
      directory:
      exceptions:
      filepath:
      fsnotify:
      http-conduit:
      lens: "^>=5.1"
      lens-aeson: "^>=1.1.3"
      mtl:
      neat-interpolation:
      optparse-applicative: "^>=0.17.0.0"
      path-io:
      path:
      pretty-simple: "^>= 4.1.2.0"
      process:
      strong-path:
      tar: "^>=0.5.1.1"
      temporary: "^>=1.3"
      text:
      time:
      unliftio: "^>= 0.2.20"
      unordered-containers: "^>= 0.2.16"
      utf8-string:
      uuid:
      waspc:
      waspls:
      zlib: "^>=0.6.3.0"

executables:
  wasp-cli:
    <<: *common_exe
    source-dirs: cli/exe
    main: Main.hs
    generated-other-modules:
      - Paths_waspc
    dependencies:
      async:
      base:
      cli-lib:
      waspc:
      with-utf8: "^>= 1.0.2"

tests:
  waspc-test:
    <<: *common_exe
    main: TastyDiscoverDriver.hs
    source-dirs: test
    build-tools:
      - tasty-discover:tasty-discover
    dependencies:
      aeson:
      base:
      bytestring:
      containers:
      deepseq:
      Diff: "^>= 0.4.1"
      filepath:
      mtl:
      neat-interpolation:
      parsec:
      path:
      QuickCheck: "^>= 2.14"
      split:
      strong-path:
      tasty: "^>= 1.4.2"
      tasty-golden: "^>= 2.3.5"
      # tasty-hspec 1.1.7 introduces breaking changes- which is why we have < 1.1.7 .
      tasty-hspec: ">= 1.1 && < 1.1.7"
      tasty-quickcheck: "^>= 0.10"
      text:
      unordered-containers:
      waspc:

  waspls-test:
    <<: *common_exe
    main: TastyDiscoverDriver.hs
    source-dirs: waspls/test
    build-tools:
      - tasty-discover:tasty-discover
    dependencies:
      base:
      bytestring:
      filepath:
      lens: "^>=5.1"
      lsp-types: "^>=1.4.0.1"
      lsp: "^>=1.4.0.0"
      mtl:
      QuickCheck: "^>= 2.14"
      tasty-golden: "^>= 2.3.5"
      # tasty-hspec 1.1.7 introduces breaking changes, which is why we have < 1.1.7 .
      tasty-hspec: ">= 1.1 && < 1.1.7"
      tasty: "^>= 1.4.2"
      waspc:
      waspls:

  cli-test:
    <<: *common_exe
    main: TastyDiscoverDriver.hs
    source-dirs: cli/test
    build-tools:
      - tasty-discover:tasty-discover
    dependencies:
      base:
      cli-lib:
      QuickCheck: "^>= 2.14"
      # tasty-hspec 1.1.7 introduces breaking changes, which is why we have < 1.1.7 .
      tasty-hspec: ">= 1.1 && < 1.1.7"
      tasty-quickcheck: "^>= 0.10"
      tasty: "^>= 1.4.2"
      waspc:

  e2e-test:
    <<: *common_exe
    main: Main.hs
    source-dirs: e2e-test
    build-tools:
      - waspc:wasp-cli
    dependencies:
      aeson-pretty:
      aeson:
      base:
      bytestring:
      dir-traverse:
      directory:
      filepath:
      mtl:
      process:
      strong-path:
      tasty-golden: "^>= 2.3.5"
      # tasty-hspec 1.1.7 introduces breaking changes, which is why we have < 1.1.7 .
      tasty-hspec: ">= 1.1 && < 1.1.7"
      tasty: "^>= 1.4.2"
      text:
      waspc:
