name: Setup Wasp CLI
description: |
  This action build on setuo-haskell action, and further sets up node.
  Then it installs the Wasp dependencies followed by installt the Wasp CLI.

inputs:
  node-version:
    description: |
      The version of Node to install.
    required: false
    default: "lts/*"

  # Inherited from setup-haskell, without default values.
  ghc-version:
    description: |
      The version of GHC to install.
    required: false

  cabal-version:
    description: |
      The version of Cabal to install.
    required: false

  cabal-project-dir:
    description: |
      The working directory for the action.
    required: false

  extra-cache-key-segment:
    description: |
      An extra key to use for the Haskell cache. Mainly used to keep glibc and musl
      caches separate, as they are not compatible.
    required: false

runs:
  using: composite

  steps:
    # - uses: "actions/checkout@v4"
    #   with:
    #     # Workaround for a Github Checkout action bug
    #     # https://github.com/actions/checkout/issues/1359#issuecomment-1567902034
    #     ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Haskell
      uses: ./.github/actions/setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        cabal-project-dir: waspc
        extra-cache-key-segment: ${{ inputs.extra-cache-key-segment }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Compile TS packages and move it into the Cabal data dir
      shell: bash
      working-directory: waspc
      run: tools/install_packages_to_data_dir.sh

    - name: Build external dependencies
      shell: bash
      working-directory: waspc
      run: cabal build --enable-tests --enable-benchmarks --only-dependencies

    - name: Build wasp code
      shell: bash
      working-directory: waspc
      run: cabal build all

    - name: Install Wasp CLI
      shell: bash
      working-directory: waspc
      id: headless-install-wasp-cli
      run: cabal install