name: Test Wasp Deploy

on:
  workflow_call:
    # secrets:
    #   FLY_API_TOKEN:
    #     description: "Fly API token for deploying apps"
    #     required: true

jobs:
  echo_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Deploying
        run: |
          echo "Deploying with secret $FLY_API_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Echo Testing
        run: echo "Testing"

      - name: Echo Destroying
        run: echo "Destroying"
