name: Test Wasp Deploy

on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        description: "Fly API token for deploying apps"
        required: true

jobs:
  echo_steps:
    runs-on: ubuntu-latest
    env:
      # TODO: When exactly does this get passed in automatically? I'm guessing whenever the workflow is called on its own (and not as a reusable workflow).
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_REGION: mia
    steps:

      - name: Install Wasp
        # TODO: I should use the currently built version, check with Franjo and Carlos.
        # This will do for now.
        run: |
          curl -sSfL https://get.wasp.sh/installer.sh | sh -s

      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Generate unique prefix
        id: generate_prefix
        run: echo "PREFIX=ci-$(openssl rand -hex 4)" >> $GITHUB_ENV

      - name: Secret sanity check
        run: echo "Passed in secret -> $FLY_API_TOKEN"

      - name: Echo Deploying
        run: |
          echo "Deploying with FLY_API_TOKEN -> $FLY_API_TOKEN"
          echo "Using prefix -> $PREFIX"
          echo "Region -> $FLY_REGION"
          echo "Github run ID -> $GITHUB_RUN_ID"
          echo "github run number -> $GITHUB_RUN_NUMBER"
          echo "Github sha -> $GITHUB_SHA"

      - name: Deploy App
        run: |
          echo Running wasp deploy fly launch $PREFIX $FLY_REGION --org wasp

      - name: Echo Testing
        run: echo "Testing"

      - name: Destroy Apps
        run: |
          echo "Running fly apps list -q | grep $PREFIX | xargs fly apps destroy -y"
