name: Test Wasp Deploy

on:
  workflow_call:
    secrets:
      # TODO: Is this the convention? deploy-examples uses capital letters
      FLY_API_TOKEN:
        description: "Fly API token for deploying apps"
        required: true

jobs:
  echo_steps:
    runs-on: ubuntu-latest
    env:
      # TODO: When exactly does this get passed in automatically? I'm guessing whenever the workflow is called on its own (and not as a reusable workflow).
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Secret sanity check
        run: |
          echo Passed in secret: $FLY_API_TOKEN

      - name: Echo Deploying
        run: echo "Deploying with FLY_API_TOKEN -> $FLY_API_TOKEN"

      - name: Echo Testing
        run: echo "Testing"

      - name: Echo Destroying
        run: echo "Destroying"
