name: Test Setup Wasp CLI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  WASP_TELEMETRY_DISABLE: 1

defaults:
  run:
    shell: bash
    working-directory: waspc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Wasp
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # We are using a fixed Ubuntu version instead of 'ubuntu-latest' to
          # prevent the version from changing on its own.
          #
          # We also set the Ubuntu version to the oldest supported LTS version
          # rather than the latest LTS version. Doing so avoids GLIBC version
          # mismatch errors (and possibly other similar issues).
          #
          # This might become redundant if we start building with Alpine/Musl
          # and link the binaries statically:
          # https://github.com/wasp-lang/wasp/issues/650#issuecomment-1180488040
          - ubuntu-22.04
          - macos-13
          - windows-latest
        node-version:
          - "lts/*"
        ghc:
          - "8.10.7"
        cabal:
          - "3.6.2.0"
        # In addition to the default matrix, we also want to run the build job for
        # additional Node.js versions, to make sure that Wasp works with them.
        # To reduce the number of jobs, we only test the Node.js versions on
        # Ubuntu 20.04.
        include:
          - os: ubuntu-22.04
            node-version: 20
            ghc: "8.10.7"
            cabal: "3.6.2.0"
          - os: ubuntu-22.04
            node-version: 22
            ghc: "8.10.7"
            cabal: "3.6.2.0"

    steps:
      - name: Configure git
        working-directory: ~
        # For waspc parser tests, we need to make sure git doesn't convert line
        # endings to CRLF during checkout on Windows because that would cause
        # the test cases to fail.
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - uses: "actions/checkout@v4"
        with:
          # Workaround for a Github Checkout action bug
          # https://github.com/actions/checkout/issues/1359#issuecomment-1567902034
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Wasp CLI
        uses: ./.github/actions/setup-wasp-cli
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          node-version: ${{ matrix.node-version }}
          cabal-project-dir: waspc

      - name: Test Installation
        run: |
          wasp-cli version
