name: Test Wasp Deploy

on:
  workflow_call:
    secrets:
      fly-token:
        description: "Fly API token for deploying apps"
        required: true

jobs:
  echo_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Deploying
        run: |
          echo Deploying with secret $TEST2
        env:
          TEST2: ${{ secrets.token }}

      - name: Echo Testing
        run: echo "Testing"

      - name: Echo Destroying
        run: echo "Destroying"
