name: Test Wasp Deploy

on:
  workflow_call:
    secrets:
      fly-api-token:
        description: "Fly API token for deploying apps"
        required: true

jobs:
  echo_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Secret sanity check
        run: |
          echo Passed in secret: $FLY_API_TOKEN_1
          echo Injected secret: $FLY_API_TOKEN_2
        env:
          FLY_API_TOKEN_1: ${{ secrets.fly-api-token }}
          FLY_API_TOKEN_2: ${{ secrets.FLY_API_TOKEN }}

      - name: Echo Deploying
        run: echo "Deploying"

      - name: Echo Testing
        run: echo "Testing"

      - name: Echo Destroying
        run: echo "Destroying"
